"""
Quant model - atomic semantic unit of memory.
"""
from datetime import datetime
from enum import Enum
from typing import Dict, Any, Optional, List
from pydantic import BaseModel, Field


class QuantType(str, Enum):
    """Types of quants in the memory system."""
    NPC = "npc"  # Characters, people
    LOCATION = "location"  # Places, areas
    ITEM = "item"  # Objects, artifacts
    FACTION = "faction"  # Groups, organizations
    EVENT = "event"  # Past events, completed actions
    SCENE = "scene"  # Specific story moments, narrative sequences
    QUEST = "quest"  # Missions, tasks
    PROMISE = "promise"  # Agreements, intentions, delayed actions ("will do later")
    CONCEPT = "concept"  # Abstract ideas, rules, systems
    OTHER = "other"  # Uncategorized


class Quant(BaseModel):
    """
    Quant - atomic semantic unit of memory.
    
    Represents entities, events, relationships, states in the agent's world.
    """
    id: str = Field(..., description="Unique identifier (name) of the quant")
    type: QuantType = Field(default=QuantType.OTHER, description="Type of the quant")
    synopsis: Optional[str] = Field(default=None, description="Short summary with =markers= for quick navigation")
    body: Dict[str, Any] = Field(default_factory=dict, description="Free-form content of the quant")
    links: Dict[str, str] = Field(default_factory=dict, description="Semantic links to other quants")
    aliases: List[str] = Field(default_factory=list, description="Alternative names for this quant")
    
    # Metadata
    created_at: Optional[int] = Field(default=None, description="Turn number when created")
    updated_at: Optional[int] = Field(default=None, description="Turn number when last updated")
    is_game: bool = Field(default=False, description="Whether this is a game-specific quant")
    
    class Config:
        json_schema_extra = {
            "example": {
                "id": "Маша",
                "type": "npc",
                "body": {
                    "reference": "Хината Хьюго из Наруто",
                    "role": "официантка",
                    "notes": "тихая, наблюдательная"
                },
                "links": {
                    "Таверна Атарикс": "работает официанткой",
                    "Ремесленный квартал": "живет неподалеку"
                },
                "created_at": 12,
                "updated_at": 18,
                "is_game": True
            }
        }


class QuantCommand(BaseModel):
    """
    Command to modify quants, generated by Quantizer agent.
    
    Format: action_quantId_path: value
    Examples:
    - create_Елена: {full quant JSON}
    - append_Маша_body_notes: "помогла игроку"
    - replace_Маша_links_Таверна_Атарикс: "уволилась"
    - delete_Старый_Квант: null
    """
    raw_command: str
    action: str  # create, append, replace, delete
    quant_id: str
    path: Optional[str] = None
    value: Any = None
    
    @classmethod
    def parse(cls, command_str: str, value: Any) -> "QuantCommand":
        """Parse command string into structured command."""
        parts = command_str.split("_", 2)
        
        if len(parts) < 2:
            raise ValueError(f"Invalid command format: {command_str}")
        
        action = parts[0]
        quant_id = parts[1]
        path = parts[2] if len(parts) > 2 else None
        
        return cls(
            raw_command=command_str,
            action=action,
            quant_id=quant_id,
            path=path,
            value=value
        )

